# Generated by Django 4.2 on 2023-07-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(blank=True, max_length=250, upload_to='images/')),
                ('additional_images', models.ManyToManyField(blank=True, related_name='projects', to='portfolio_website.additionalimage')),
            ],
        ),
        migrations.AddField(
            model_name='additionalimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additionalimages', to='portfolio_website.project'),
        ),
    ]
