# Generated by Django 4.2 on 2023-07-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0002_alter_project_category_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='info',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(max_length=250, upload_to='images/'),
        ),
    ]
