# Generated by Django 4.2 on 2023-07-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0003_project_info_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.TextField(max_length=250),
        ),
    ]
