# Generated by Django 4.2 on 2023-07-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0005_project_slug_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(),
        ),
    ]
