# Generated by Django 4.2 on 2023-07-18 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_website', '0006_alter_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='project',
            name='additional_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio_website.additionalimage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
